version: '3.6'

services:

  db:
    image: postgres
    volumes:
      - pslq-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass

  adminer:
    image: adminer
    ports:
      - 8081:8080

  web:
    build:
      context: .
      cache_from:
        - tomcat:latest
    image: hvits3rk/tomcat-no-root:latest
    ports:
      - 8080:8080
    volumes:
      - ./deploy/gb-spring1-adsite-0.1.war:/usr/local/tomcat/webapps/ROOT.war

volumes:
  pslq-data: